### ISSUE TITLE
testing a bunch of nested callbacks using bcrypt and redis 

### ISSUE THREAD

**Issue by des-des** [FAC6/facfaq#4]
@nelsonic 
If you broke if statement here: https://github.com/des-des/aibox/blob/master/server/authenticator.js#L9 into three different branches for different ways to handle errors how would you test them? at the moment I am faking it so that I only test one of those three possible errors...

**Comment by nelsonic** [comment]
@des-des you aren't really _doing_ anything with the errors...
https://github.com/des-des/aibox/blob/32f0b0d483799bb319b9e5566a9a9bdba588fe29/server/authenticator.js#L13
if _instead_ you:

``` js
var error = saltError || hashError || false;
return callback(error, result);
```

That way you can write a test that checks (tests) for each of the errors.
Have you had a look at https://www.joyent.com/developers/node/design/errors ?

**Comment by des-des** [comment]
Thanks, great reading! I think I was not super clear with my problem. The problem way that I was unsure of how to get full test coverage when I did not know how to get bcrypt to throw errors. But yeah your soln much more elegant then what I am doing. (easy solution to finding out when bcrypt throws errors was to look at the source..)

**Comment by nelsonic** [comment]
![high five](http://chatabout.com/assets/images/questions/2014/07/53c0790b40514.jpg)
