### ISSUE TITLE
set of asyncs called by set of asyncs!

### ISSUE THREAD

**Issue by des-des** [FAC6/facfaq#5]
## Problem

I am trying to apply a pattern something like this:

```
var setThreeNumbersAsync = function(nums, callback) {
  var numbersFetched = 0;
  out = [];
  var next = function(number, index) {
    out[index] = number;
    numbersFetched += 1;
    if (numbersFetched === 3) {
      callback(out);
    }
  };
  setTimeout(function() {
    next(nums[0], 0);
  }, 100);
  setTimeout(function() {
    next(nums[1], 1);
  }, 200);
  setTimeout(function() {
    next(nums[2], 2);
  }, 300);
};

setThreeNumbersAsync([0, 1, 2], function(result) {
  console.log('0, 1, 2 set at time 0: ', result);
});

setTimeout(function() {
  setThreeNumbersAsync([3, 4, 5], function(result) {
    console.log('3, 4, 5 set at time 0.1: ', result);
  });
}, 50);
```

As _expected_ the out put is this:

```
"0, 1, 2 set at time 0: "
[3, 4, 2]
"3, 4, 5 set at time 0.05: "
[3, 4, 5]
```

What is a nice way to do this. ie `setThreeNumbersAsync` is used/modified in such a way that each call made to it that holds a separate instance of out.
## possible solutions
- use `new` (but that would upset crockford)
- have an array of arrays for `out`; each outer array referenced by a counter incremented on each call to `setThreeNumbersAsync` (plus some closure trickery)
## questions
- Is the second solution the best way to do things without using `new`? 
- Does this problem make sense?

**Comment by rjmk** [comment]
I'm not sure I understand the question. The code as written could simply be modified on line 3 to read `var out = []` and this would keep `out` different with each call. I don't think this is what you're looking for though ...

**Comment by des-des** [comment]
derp. Ok this is not my problem, just a typo in my example...

**Comment by rjmk** [comment]
@des-des I thought that was probably the case. Do reopen with an example that clarifies your problem!

**Comment by des-des** [comment]
ok need to do some bug hunting

**Comment by des-des** [comment]
@rjmk ok my issue was exactly as you pointed out. https://github.com/dwyl/adoro/blob/engine/lib/markdown-amp.js#L7

**Comment by nelsonic** [comment]
:+1:

**Comment by rjmk** [comment]
Happy to be a rubber duck
