### ISSUE TITLE
Running a callback after forEach

### ISSUE THREAD

**Issue by hdrdavies** [FAC6/facfaq#8]
How do you run a callback which waits for a `forEach` function to finish before it is called?

**Comment by iteles** [comment]
@hdrdavies `forEach` is sync. see: http://ecma262-5.com/ELS5_HTML.htm#Section_15.4.4.18
which means you can put your callback on the next line _after_ it has run.
(_unless you are running a bunch of `async` calls inside the `forEach` block...?_)

**Comment by hdrdavies** [comment]
@iteles Yes you're right - we did see that here too: 

http://stackoverflow.com/questions/18983138/callback-after-foreach-is-done

But we're trying to populate an array above the `forEach` function (using `arr.push()` inside the `forEach`), and then create a object using that array (after the `forEach` function). The object is created before the `forEach` is finished, with an empty array which hasn't been populated by the `push` method yet- so it doesn't work, hence why we felt the need for a callback......

**Comment by iteles** [comment]
Is your code on GitHub?

**Comment by hdrdavies** [comment]
yep! [Here](https://github.com/HMS-FAC/BoatlaunchMVP/blob/cluster/views/map.js#L56)! As you can see, the problem is currently being solved with a `setTimeout` function [here](https://github.com/HMS-FAC/BoatlaunchMVP/blob/cluster/views/map.js#L134).

**Comment by hdrdavies** [comment]
Solved! As usual, I should have just asked @des-des :laughing:

**Comment by nelsonic** [comment]
@hdrdavies when posting links to code, please add `commit` hash so that the link is preserved when you update the code... (makes this question useful to others...)

**Comment by iteles** [comment]
@hdrdavies FYI If you're in a file, just press the 'Y' key and it'll insert e current commit ID into the URL

**Comment by hdrdavies** [comment]
@iteles Thanks for the top tip! @nelsonic quite right, my problem was that I was locating the clusterer [here](https://github.com/HMS-FAC/BoatlaunchMVP/blob/82bfbe44a3598f21ece51b1e2a234b59f80f74ab/views/map.js#L133) when I should have been doing it [here](https://github.com/HMS-FAC/BoatlaunchMVP/blob/7c0c2c0d79fdf542d3059e778415c6a0a9a0b6f2/views/map.js#L81), within the callback but after the `forEach`. Forgive the messy code, it's since been cleaned up!
